# This is workflow name
name: Hello Workflow
# Runs on an automatic trigger, whenever changes is pushed to branch [Deployment]
on:
  push:
    branches: [main]
# These are the jobs inside the workflow
jobs:
  # This is the name of the job
  greet:
    # This is github runner. Each jobs run on a runner (server-> ubuntu/windows/macos etc)
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - name: say hello to users
        run: echo "Hello Dosto"
      # Step 2
      - name: say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: version of python, etc
        run: docker --version && python --version
